version: '3.3'
services:
  blackarch-zsh:
    container_name: blackarch-zsh
    image: cloufish/blackarch-zsh:latest
    hostname: blackarch-zsh
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'

  blackarch-zsh-iot:
    container_name: bug-bounty-framework-iot
    image: cloufish/bug-bounty-framework-iot:latest
    hostname: bug-bounty-framework-iot
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'
      
  blackarch-zsh-minimal:
    container_name: bug-bounty-framework-mobile
    image: cloufish/bug-bounty-framework-mobile:latest
    hostname: bug-bounty-framework-mobile
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'

  mobile-security-framework-mobsf:
      ports:
        - '8000:8000'
      image: 'opensecurity/mobile-security-framework-mobsf:latest'
      restart: unless-stopped
      stdin_open: true
      tty: true
      volumes:
        - '~/.local/share/MobSF:/root/.MobSF'

  drozer:
    container_name: drozer
    image: fsecurelabs/drozer
    hostname: drozer
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: bash -c "drozer console connect"

  bug-bounty-framework-web:
    container_name: bug-bounty-framework-web
    image: cloufish/bug-bounty-framework-web:latest
    hostname: bug-bounty-framework-web
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'
  couchdb:
    hostname: couchdb
    image: honoki/bbrf-server
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=penelope    # please please please replace this with a secure password
      - BBRF_PASSWORD=penelope    # please please please replace this with a secure password
    volumes:
      - ~/.data/couchdb/1:/opt/couchdb/data
  proxy:
    image: nginx
    hostname: proxy
    ports:
      - "9001:443"
    volumes:
        - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./proxy/docker-entrypoint.d/:/docker-entrypoint.d/
        - ./proxy/keys/:/etc/nginx/keys/
    depends_on:
      - couchdb