version: '3.3'
services:
  blackarch-zsh-minimal:
    container_name: bug-bounty-framework-mobile
    image: cloufish/bug-bounty-framework-mobile:latest
    hostname: bug-bounty-framework-mobile
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'

  mobile-security-framework-mobsf:
      ports:
        - '8000:8000'
      image: 'opensecurity/mobile-security-framework-mobsf:latest'
      restart: unless-stopped
      stdin_open: true
      tty: true
      volumes:
        - '~/.local/share/MobSF:/root/.MobSF'

  drozer:
    container_name: drozer
    image: fsecurelabs/drozer
    hostname: drozer
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: bash -c "drozer console connect"
