version: '3.3'
services:
  blackarch-zsh-minimal:
    container_name: bug-bounty-framework-mobile
    image: cloufish/bug-bounty-framework-mobile:latest
    hostname: bug-bounty-framework-mobile
    ports:
      - '80:80'
      - '443:443'
      - '20:20'
      - '21:21'
      - '22:22'
      - '8080:8080'
      - '1337:1337'
      - '4444:4444'
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'
