version: '3.3'
services:
  blackarch-zsh-minimal:
    container_name: bug-bounty-framework-mobile
    image: cloufish/bug-bounty-framework-mobile:latest
    hostname: bug-bounty-framework-mobile
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
 services:
    mobile-security-framework-mobsf:
        ports:
            - '8000:8000'
        image: 'opensecurity/mobile-security-framework-mobsf:latest'
     - '~/Downloads:/home/penelope/Downloads'
