version: '3.3'
services:
  blackarch-zsh-minimal:
    container_name: bug-bounty-framework-iot
    image: cloufish/bug-bounty-framework-iot:latest
    hostname: bug-bounty-framework-iot
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'