---
version: '3.9'
services:
  bug-bounty-framework-web:
    container_name: bug-bounty-framework-web
    image: cloufish/bug-bounty-framework-web:latest
    hostname: bug-bounty-framework-web
    ports:
      - '80:80'
      - '443:443'
      - '20:20'
      - '21:21'
      - '22:22'
      - '8080:8080'
      - '1337:1337'
      - '4444:4444'
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
      - '~/Downloads:/home/penelope/Downloads'
  couchdb:
    hostname: couchdb
    image: honoki/bbrf-server
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=penelope    # please please please replace this with a secure password
      - BBRF_PASSWORD=penelope    # please please please replace this with a secure password
    volumes:
      - ~/.data/couchdb/1:/opt/couchdb/data
  proxy:
    image: nginx
    hostname: proxy
    ports:
      - "9001:443"
    volumes:
        - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./proxy/docker-entrypoint.d/:/docker-entrypoint.d/
        - ./proxy/keys/:/etc/nginx/keys/
    depends_on:
      - couchdb
