version: '3.3'
services:
  blackarch-zsh-minimal:
    container_name: blackarch-zsh-minimal
    image: cloufish/blackarch-zsh-minimal:latest
    hostname: blackarch-zsh
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
