version: '3.3'
services:
  blackarch-zsh:
    container_name: blackarch-zsh
    image: blackarch-zsh
    hostname: blackarch-zsh
    ports:
      - '80:80'
      - '443:443'
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
