version: '3.3'
services:
  blackarch-zsh:
    container_name: blackarch-zsh
    image: cloufish/blackarch-zsh:latest
    hostname: blackarch-zsh
    ports:
      - '80:80'
      - '443:443'
      - '20:20'
      - '21:21'
      - '22:22'
      - '8080:8080'
      - '1337:1337'
      - '4444:4444'
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '~/Pentesting:/home/penelope/Pentesting'
