name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
   - cron: '0 0 * * *'
jobs:

  blackarch-zsh:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cloufish/blackarch-zsh:latest
      working-directory: ./blackarch-zsh
    - name: Docker Push
      run: docker push cloufish/blackarch-zsh
  blackarch-zsh-minimal:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cloufish/blackarch-zsh-minimal:latest
      working-directory: ./blackarch-zsh-minimal
    - name: Docker Push
      run: docker push cloufish/blackarch-zsh-minimal
      
  bug_bounty_framework_web:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cloufish/bug-bounty-framework-web:latest
      working-directory: ./bug-bounty-framework-web
    - name: Docker Push
      run: docker push cloufish/bug-bounty-framework-web
